const PUT_ALL_POSTS = "PUT_ALL_POSTS";
const PUT_POST_By_ID = "PUT_POST_By_ID";
const AD_TO_ALL_POSTS = "AD_TO_ALL_POSTS";
const DELETE_POST = "DELETE_POST";
const PUT_NEW_COMMENT = "PUT_NEW_COMMENT";
const SET_LOADING = "SET_LOADING";

export {
  SET_LOADING,
  DELETE_POST,
  PUT_POST_By_ID,
  PUT_ALL_POSTS,
  AD_TO_ALL_POSTS,
  PUT_NEW_COMMENT
};
