const PUT_ALL_POSTS = "PUT_ALL_POSTS";
const PUT_POST_By_ID = "PUT_POST_By_ID";
const ADD_TO_ALL_POSTS = "ADD_TO_ALL_POSTS";
const DELETE_POST = "DELETE_POST";
const PUT_NEW_COMMENT = "PUT_NEW_COMMENT";
const ERROR = "ERROR";

export { DELETE_POST, PUT_POST_By_ID, PUT_ALL_POSTS, ADD_TO_ALL_POSTS, PUT_NEW_COMMENT, ERROR };
